openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "To-Do Application"
  description: "API documentation for To-Do application"
  contact:
    email: "fajri.apk@gmail.com"
servers:
  - url: "http://{host}:8080"

paths:
  /v1/projects:
    post:
      summary: "Create a project"
      description: "Create a project with a name and a description"
      deprecated: false
      tags:
        - CREATE
      parameters:
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
          example: 'application/json'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProject"
      responses:
        200:
          description: "Success creating project"
          content:
            application/json:
              examples:
                "Success":
                  value:
                    success: true
                    data:
                      project_id: "project_id"
        400:
          description: "Bad request"
          content:
            application/json:
              examples:
                "Did not send name, description, or both":
                  value:
                    success: false
                    data: {}
                    errors: "name_or_description_empty"
                "Sent empty name, empty description, or both":
                  value:
                    success: false
                    data: {}
                    errors: "name_or_description_empty"
  /v1/projects/{projectId}:
    post:
      summary: "Create an item"
      description: "Create an item with a name and a description"
      deprecated: false
      tags:
        - CREATE
      parameters:
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
          example: 'application/json'
        - name: projectId
          in: path
          required: true
          description: ''
          schema:
            type: string
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateItem"
      responses:
        200:
          description: "Success creating item"
          content:
            application/json:
              examples:
                "Success":
                  value:
                    success: true
                    data:
                      item_id: "item_id"
        400:
          description: "Bad request"
          content:
            application/json:
              examples:
                "Did not send name, description, or both":
                  value:
                    success: false
                    data: {}
                    errors: "name_or_description_empty"
                "Sent empty name, empty description, or both":
                  value:
                    success: false
                    data: {}
                    errors: "name_or_description_empty"
                "Invalid project ID":
                  value:
                    success: false
                    data: {}
                    errors: "error string"
        500:
          description: "Could not save item"
          content:
            application/json:
              examples:
                "Invalid project ID":
                  value:
                    success: false
                    data: {}
                    errors: "error string"
    get:
      summary: "Get details of a project"
      description: "List a project's name, description, and items"
      deprecated: false
      tags:
        - READ
      parameters:
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
          example: 'application/json'
        - name: projectId
          in: path
          required: true
          description: ''
          schema:
            type: string
          example: 1
      responses:
        200:
          description: "Success getting the project"
          content:
            application/json:
                schema:
                  $ref: "#/components/schemas/GetProjectResponse"
        400:
          description: "Bad request"
          content:
            application/json:
              examples:
                "Could not find project":
                  value:
                    success: false
                    data: {}
                    errors: "error string"
  /v1/projects/{projectId}/{itemId}:
    get:
      summary: "Get details of an item"
      description: "List an item's name and description"
      deprecated: false
      tags:
        - READ
      parameters:
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
          example: 'application/json'
        - name: projectId
          in: path
          required: true
          description: ''
          schema:
            type: string
          example: 1
        - name: itemId
          in: path
          required: true
          description: ''
          schema:
            type: string
          example: 1
      responses:
        200:
          description: "Success getting the item"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetItemResponse"
        400:
          description: "Bad request"
          content:
            application/json:
              examples:
                "Could not find matching project ID and item ID":
                  value:
                    success: false
                    data: {}
                    errors: "error string"

components:
  schemas:
    CreateProject:
      type: "object"
      properties:
        name:
          type: "string"
          description: "Non-empty project name"
        description:
          type: "string"
          description: "Non-empty project description"
      required:
        - name
        - description
    CreateItem:
      type: "object"
      properties:
        name:
          type: "string"
          description: "Non-empty item name"
        description:
          type: "string"
          description: "Non-empty item description"
      required:
        - name
        - description
    GetProjectResponse:
      type: "object"
      properties:
        success:
          type: "string"
          description: "Response status"
          example: true/false
        data:
          type: "object"
          description: "Get project response data"
          properties:
            project_id:
              type: "integer"
              description: "Project ID"
              example: 1
            name:
              type: "string"
              description: "Non-empty project name"
            description:
              type: "string"
              description: "Non-empty project description"
            items:
              type: "array"
              description: "Items belonging to the project"
              items:
                type: "object"
                description: "Item"
                properties:
                  item_id:
                    type: "integer"
                    description: "Item ID"
                    example: 1
                  name:
                    type: "string"
                    description: "Item name"
        error:
          type: "string"
          description: "Error description"
    GetItemResponse:
      type: "object"
      properties:
        success:
          type: "string"
          description: "Response status"
          example: true/false
        data:
          type: "object"
          description: "Get item response data"
          properties:
            item_id:
              type: "integer"
              description: "Item ID"
              example: 1
            name:
              type: "string"
              description: "Non-empty item name"
            description:
              type: "string"
              description: "Non-empty item description"
        error:
          type: "string"
          description: "Error description"
